// <auto-generated />
using FinalProject_BJSS5.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject_BJSS5.Migrations
{
    [DbContext(typeof(FinalContext))]
    partial class FinalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FinalProject_BJSS5.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublishYear")
                        .HasColumnType("int");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Louisa May Alcott",
                            Name = "Bidhatri",
                            PublishYear = 1868,
                            Publisher = "Simon & Schuster",
                            Title = "Little Women"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Satoshi Yagisawa",
                            Name = "Jasmine",
                            PublishYear = 2023,
                            Publisher = "Harper Perennial",
                            Title = "Days at the Morisaki Bookshop"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Victor Hugo",
                            Name = "Sage",
                            PublishYear = 1862,
                            Publisher = "A. Lacroix, Verboeckhoven & Cie.",
                            Title = "Les Miserables"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Noel Streatfeild",
                            Name = "Sydney",
                            PublishYear = 1936,
                            Publisher = "J. M. Dent & Sons",
                            Title = "Ballet Shoes"
                        });
                });

            modelBuilder.Entity("FinalProject_BJSS5.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Food")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Movie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Favorites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Purple",
                            Drink = "Bubble Tea",
                            Food = "Cheesecake",
                            Movie = "Pride and Prejudice",
                            Name = "Bidhatri"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Green",
                            Drink = "Matcha",
                            Food = "Sushi",
                            Movie = "The Meg 2",
                            Name = "Jasmine"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Blue",
                            Drink = "Gold Peak Tea",
                            Food = "Mashed Potatoes",
                            Movie = "First Blood",
                            Name = "Sage"
                        },
                        new
                        {
                            Id = 4,
                            Color = "grey",
                            Drink = "Water",
                            Food = "Cucumber",
                            Movie = "Z-O-M-B-I-E-S",
                            Name = "Sydney"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
